### ISSUE TITLE
Flag provided but not defined: -login.okta.directory.api-token

### ISSUE THREAD

**Issue by usefree** [redpanda-data/kowl#361]
Hello, and thanks for Your product. I tried to setup kowl business with trial license here is my values:
``` 
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kowl-business
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: kowl
      version: '2.3.0'
      sourceRef:
        kind: HelmRepository
        name: cloudhunt
        namespace: flux-system
      interval: 1m
 values:
    resources:
      limits:
        memory: 3Gi
      requests:
        cpu: 200m
        memory: 256Mi
    secret:
      existingSecret: kowl-business
    image:
      registry: quay.io
      repository: cloudhut/kowl-business
      tag: v1.5.0
    fullnameOverride: "kowl-business"
    kowl:
      config:
        kafka:
          brokers:
            - kafka.net.private:9092
          tls:
            enabled: false 
        business:
          rolesFilepath: /etc/kowl/configs/roles.yaml 
          roleBindingsFilepath: /etc/kowl/configs/role-bindings.yaml 
          auditLog:
            enabled: true
        login:
          github:
            enabled: true
            clientId: Iv1.redacted
      roles:
        - name: developer
          permissions:
            - resource: consumerGroups
              includes: ["/.*/"]
              allowedActions: ["viewer"]
            - resource: topics
              includes: ["/.*/"]
              allowedActions: ["viewer"]
            - resource: cluster
              allowedActions: ["viewAcl"]
      roleBindings:
        - metadata:
            name: Kowl Developers
          subjects:
            - kind: user
              provider: GitHub
              name: usefree
          roleName: developer
``` 
and secret:
``` apiVersion: v1
kind: Secret
metadata:
  name: kowl-business
  namespace: monitoring
type: Opaque
data:
  # CloudHut
  cloudhut-license-token: "ZXlKaGJHY2lP...MmRXalYwbk0yRWZBCg=="
  login-github-personal-access-token: "Z2hwX...F2MAo="
  kafka-tls-passphrase: ""
  kafka-sasl-password: ""
  kafka-tls-ca: ""
  kafka-tls-cert: ""
  kafka-tls-key: ""
  login-jwt-secret: ""
  login-google-oauth-client-secret: ""
  login-google-groups-service-account.json: ""
  login-github-oauth-client-secret: ""
  login-okta-client-secret: ""
  login-okta-directory-api-token: "MQo="
```

as mentioned here https://github.com/cloudhut/charts/blob/bc1b86a6aa8875cfcb6bc94c6e86038c51e4af5d/kowl/values.yaml#L115 i defined all the variables, even not planing to use them. And Among variables there is "login-okta-directory-api-token". But when chart is installed there is error appeared in pod logs:
`flag provided but not defined: -login.okta.directory.api-token`.
And if not to define "login-okta-directory-api-token" in the secret, there is another error appeared :
` kubelet            Error: couldn't find key login-okta-directory-api-token in Secret monitoring/kowl-busines`

As a result chart is not installed. How to deal with that?

**Comment by weeco** [comment]
Hey @usefree ,
that's exactly (I think the only) issue we fixed in v1.5.1. Could you please try docker version v1.5.1 or even one of the more recent ones like `master-c68ab72`? See: https://quay.io/repository/cloudhut/kowl-business?tag=latest&tab=tags

**Comment by usefree** [comment]
@weeco  thanks a lot, seems like it helps, and i made some additional fixes, after them all i got such a working secret
```
apiVersion: v1
kind: Secret
metadata:
  name: kowl-business
  namespace: monitoring
type: Opaque
data:
  # CloudHut
  cloudhut-license-token: "ZXlKaGJHY2lP...MmRXalYwbk0yRWZBCg=="
  login-github-personal-access-token: "Z2hwX...F2MAo="
  kafka-sasl-password: ""
  kafka-tls-ca: ""
  kafka-tls-cert: ""
  kafka-tls-key: ""
  kafka-tls-passphrase: ""
  login-github-oauth-client-secret: ZDU0N...EwYQo=
  login-github-personal-access-token: Z2hwX29...2MAo=
  login-google-groups-service-account.json: ""
  login-google-oauth-client-secret: ""
  login-jwt-secret: MQo=
  login-okta-client-secret: ""
  login-okta-directory-api-token: MQo=
```
, but now i got error in logs 
`{"level":"fatal","ts":"2022-05-04T17:34:33.972Z","msg":"failed to create hooks","error":"failed to validate cloudhut license: failed to get license: rpc error: code = Unknown desc = failed to validate license: failed to parse the token: illegal base64 data at input byte 88"}`

**Comment by weeco** [comment]
@usefree Cool! Could you double check whether the token that is given into the config for Kowl is valid? E.g. no hidden linebreak, space etc. at the end. You could also additional validate the token against https://jwt.io/ to see if it is decoable.

**Comment by usefree** [comment]
@weeco thanks again, i started the pod in k8s, now, when i tried to login with github i received error 
` Error: redirect_uri_mismatch
Description: The redirect_uri MUST match the registered callback URL for this application.`
my kowl ingress in k8s is `http://kowl-business.kube.my-domain.org/` and in settings of the app in github organization i configured  `http://kowl-business.kube.my-domain.org/login/callbacks/github`  
could You please, guess what is wrong ?
Thanks a lot!

**Comment by weeco** [comment]
Hmm that might be related to your http (non-ssl) url. You can see what Kowl passes as the expected callback url if you open the network tab and load the login scren. There is a request to /auth/providers and that response body contains a JSON. For each configured login provider it will have a URL.

This URL has an encoded query parameter for the redirect uri. Could you see whether this redirect uri matches what you'd expect? Specifically I wonder whether Kowl reports `https` rather than `http` (as you would probably expect for your case).

If that's the case you could try setting the following configuration at the root level of your YAML config:

```yaml
login:
  useSecureCookies: false
  // and your okta configuration goes here probably
```
